<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5M6A0B7" failures="1" tests="3" name="capstoneproject.ZeroBank.runners.PayBillsRunner" time="55.097" errors="0" timestamp="2025-03-19T01:01:12 IST" skipped="0">
  <testcase classname="capstoneproject.ZeroBank.runners.PayBillsRunner" name="runScenario" time="20.938"/>
  <testcase classname="capstoneproject.ZeroBank.runners.PayBillsRunner" name="runScenario" time="16.057">
    <failure message="Success message not displayed! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Success message not displayed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at capstoneproject.ZeroBank.stepdefinitions.PayBillsStepDefinition.user_sees_a_success_message(PayBillsStepDefinition.java:96)
at âœ½.User sees a success message(file:///C:/Users/dell/Desktop/Traning/ZeroBank2.zip_expanded/ZeroBank2/src/test/resources/features/paybills.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="capstoneproject.ZeroBank.runners.PayBillsRunner" name="runScenario" time="18.102"/>
</testsuite> <!-- capstoneproject.ZeroBank.runners.PayBillsRunner -->
